/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReleasesRouteImport } from './routes/api/releases'
import { Route as ApiChangelogRouteImport } from './routes/api/changelog'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiWebhooksProviderRouteImport } from './routes/api/webhooks/$provider'
import { Route as ApiLicensePubkeyRouteImport } from './routes/api/license/pubkey'
import { Route as ApiLicenseDeactivateRouteImport } from './routes/api/license/deactivate'
import { Route as ApiLicenseCheckRouteImport } from './routes/api/license/check'
import { Route as ApiLicenseActivateRouteImport } from './routes/api/license/activate'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppSupportRouteImport } from './routes/_auth/app/support'
import { Route as AuthAppDownloadsRouteImport } from './routes/_auth/app/downloads'
import { Route as AuthAppBillingRouteImport } from './routes/_auth/app/billing'
import { Route as ApiAdminLicenseUnrevokeRouteImport } from './routes/api/admin/license/unrevoke'
import { Route as ApiAdminLicenseRevokeRouteImport } from './routes/api/admin/license/revoke'
import { Route as ApiAdminLicenseInfoRouteImport } from './routes/api/admin/license/info'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleasesRoute = ApiReleasesRouteImport.update({
  id: '/api/releases',
  path: '/api/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChangelogRoute = ApiChangelogRouteImport.update({
  id: '/api/changelog',
  path: '/api/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiWebhooksProviderRoute = ApiWebhooksProviderRouteImport.update({
  id: '/api/webhooks/$provider',
  path: '/api/webhooks/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicensePubkeyRoute = ApiLicensePubkeyRouteImport.update({
  id: '/api/license/pubkey',
  path: '/api/license/pubkey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicenseDeactivateRoute = ApiLicenseDeactivateRouteImport.update({
  id: '/api/license/deactivate',
  path: '/api/license/deactivate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicenseCheckRoute = ApiLicenseCheckRouteImport.update({
  id: '/api/license/check',
  path: '/api/license/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicenseActivateRoute = ApiLicenseActivateRouteImport.update({
  id: '/api/license/activate',
  path: '/api/license/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppSupportRoute = AuthAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppDownloadsRoute = AuthAppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppBillingRoute = AuthAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAdminLicenseUnrevokeRoute = ApiAdminLicenseUnrevokeRouteImport.update({
  id: '/api/admin/license/unrevoke',
  path: '/api/admin/license/unrevoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLicenseRevokeRoute = ApiAdminLicenseRevokeRouteImport.update({
  id: '/api/admin/license/revoke',
  path: '/api/admin/license/revoke',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLicenseInfoRoute = ApiAdminLicenseInfoRouteImport.update({
  id: '/api/admin/license/info',
  path: '/api/admin/license/info',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/download': typeof DownloadRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/api/changelog': typeof ApiChangelogRoute
  '/api/releases': typeof ApiReleasesRoute
  '/app/billing': typeof AuthAppBillingRoute
  '/app/downloads': typeof AuthAppDownloadsRoute
  '/app/support': typeof AuthAppSupportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/license/activate': typeof ApiLicenseActivateRoute
  '/api/license/check': typeof ApiLicenseCheckRoute
  '/api/license/deactivate': typeof ApiLicenseDeactivateRoute
  '/api/license/pubkey': typeof ApiLicensePubkeyRoute
  '/api/webhooks/$provider': typeof ApiWebhooksProviderRoute
  '/app/': typeof AuthAppIndexRoute
  '/api/admin/license/info': typeof ApiAdminLicenseInfoRoute
  '/api/admin/license/revoke': typeof ApiAdminLicenseRevokeRoute
  '/api/admin/license/unrevoke': typeof ApiAdminLicenseUnrevokeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/download': typeof DownloadRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/api/changelog': typeof ApiChangelogRoute
  '/api/releases': typeof ApiReleasesRoute
  '/app/billing': typeof AuthAppBillingRoute
  '/app/downloads': typeof AuthAppDownloadsRoute
  '/app/support': typeof AuthAppSupportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/license/activate': typeof ApiLicenseActivateRoute
  '/api/license/check': typeof ApiLicenseCheckRoute
  '/api/license/deactivate': typeof ApiLicenseDeactivateRoute
  '/api/license/pubkey': typeof ApiLicensePubkeyRoute
  '/api/webhooks/$provider': typeof ApiWebhooksProviderRoute
  '/app': typeof AuthAppIndexRoute
  '/api/admin/license/info': typeof ApiAdminLicenseInfoRoute
  '/api/admin/license/revoke': typeof ApiAdminLicenseRevokeRoute
  '/api/admin/license/unrevoke': typeof ApiAdminLicenseUnrevokeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/download': typeof DownloadRoute
  '/privacy': typeof PrivacyRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/api/changelog': typeof ApiChangelogRoute
  '/api/releases': typeof ApiReleasesRoute
  '/_auth/app/billing': typeof AuthAppBillingRoute
  '/_auth/app/downloads': typeof AuthAppDownloadsRoute
  '/_auth/app/support': typeof AuthAppSupportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/license/activate': typeof ApiLicenseActivateRoute
  '/api/license/check': typeof ApiLicenseCheckRoute
  '/api/license/deactivate': typeof ApiLicenseDeactivateRoute
  '/api/license/pubkey': typeof ApiLicensePubkeyRoute
  '/api/webhooks/$provider': typeof ApiWebhooksProviderRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/api/admin/license/info': typeof ApiAdminLicenseInfoRoute
  '/api/admin/license/revoke': typeof ApiAdminLicenseRevokeRoute
  '/api/admin/license/unrevoke': typeof ApiAdminLicenseUnrevokeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/download'
    | '/privacy'
    | '/roadmap'
    | '/sitemap.xml'
    | '/terms'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/changelog'
    | '/api/releases'
    | '/app/billing'
    | '/app/downloads'
    | '/app/support'
    | '/api/auth/$'
    | '/api/license/activate'
    | '/api/license/check'
    | '/api/license/deactivate'
    | '/api/license/pubkey'
    | '/api/webhooks/$provider'
    | '/app/'
    | '/api/admin/license/info'
    | '/api/admin/license/revoke'
    | '/api/admin/license/unrevoke'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/download'
    | '/privacy'
    | '/roadmap'
    | '/sitemap.xml'
    | '/terms'
    | '/login'
    | '/signup'
    | '/api/changelog'
    | '/api/releases'
    | '/app/billing'
    | '/app/downloads'
    | '/app/support'
    | '/api/auth/$'
    | '/api/license/activate'
    | '/api/license/check'
    | '/api/license/deactivate'
    | '/api/license/pubkey'
    | '/api/webhooks/$provider'
    | '/app'
    | '/api/admin/license/info'
    | '/api/admin/license/revoke'
    | '/api/admin/license/unrevoke'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/changelog'
    | '/download'
    | '/privacy'
    | '/roadmap'
    | '/sitemap.xml'
    | '/terms'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/api/changelog'
    | '/api/releases'
    | '/_auth/app/billing'
    | '/_auth/app/downloads'
    | '/_auth/app/support'
    | '/api/auth/$'
    | '/api/license/activate'
    | '/api/license/check'
    | '/api/license/deactivate'
    | '/api/license/pubkey'
    | '/api/webhooks/$provider'
    | '/_auth/app/'
    | '/api/admin/license/info'
    | '/api/admin/license/revoke'
    | '/api/admin/license/unrevoke'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  DownloadRoute: typeof DownloadRoute
  PrivacyRoute: typeof PrivacyRoute
  RoadmapRoute: typeof RoadmapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiChangelogRoute: typeof ApiChangelogRoute
  ApiReleasesRoute: typeof ApiReleasesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLicenseActivateRoute: typeof ApiLicenseActivateRoute
  ApiLicenseCheckRoute: typeof ApiLicenseCheckRoute
  ApiLicenseDeactivateRoute: typeof ApiLicenseDeactivateRoute
  ApiLicensePubkeyRoute: typeof ApiLicensePubkeyRoute
  ApiWebhooksProviderRoute: typeof ApiWebhooksProviderRoute
  ApiAdminLicenseInfoRoute: typeof ApiAdminLicenseInfoRoute
  ApiAdminLicenseRevokeRoute: typeof ApiAdminLicenseRevokeRoute
  ApiAdminLicenseUnrevokeRoute: typeof ApiAdminLicenseUnrevokeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/releases': {
      id: '/api/releases'
      path: '/api/releases'
      fullPath: '/api/releases'
      preLoaderRoute: typeof ApiReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/changelog': {
      id: '/api/changelog'
      path: '/api/changelog'
      fullPath: '/api/changelog'
      preLoaderRoute: typeof ApiChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/webhooks/$provider': {
      id: '/api/webhooks/$provider'
      path: '/api/webhooks/$provider'
      fullPath: '/api/webhooks/$provider'
      preLoaderRoute: typeof ApiWebhooksProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/license/pubkey': {
      id: '/api/license/pubkey'
      path: '/api/license/pubkey'
      fullPath: '/api/license/pubkey'
      preLoaderRoute: typeof ApiLicensePubkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/license/deactivate': {
      id: '/api/license/deactivate'
      path: '/api/license/deactivate'
      fullPath: '/api/license/deactivate'
      preLoaderRoute: typeof ApiLicenseDeactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/license/check': {
      id: '/api/license/check'
      path: '/api/license/check'
      fullPath: '/api/license/check'
      preLoaderRoute: typeof ApiLicenseCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/license/activate': {
      id: '/api/license/activate'
      path: '/api/license/activate'
      fullPath: '/api/license/activate'
      preLoaderRoute: typeof ApiLicenseActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/support': {
      id: '/_auth/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AuthAppSupportRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/downloads': {
      id: '/_auth/app/downloads'
      path: '/downloads'
      fullPath: '/app/downloads'
      preLoaderRoute: typeof AuthAppDownloadsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/billing': {
      id: '/_auth/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthAppBillingRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/admin/license/unrevoke': {
      id: '/api/admin/license/unrevoke'
      path: '/api/admin/license/unrevoke'
      fullPath: '/api/admin/license/unrevoke'
      preLoaderRoute: typeof ApiAdminLicenseUnrevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/license/revoke': {
      id: '/api/admin/license/revoke'
      path: '/api/admin/license/revoke'
      fullPath: '/api/admin/license/revoke'
      preLoaderRoute: typeof ApiAdminLicenseRevokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/license/info': {
      id: '/api/admin/license/info'
      path: '/api/admin/license/info'
      fullPath: '/api/admin/license/info'
      preLoaderRoute: typeof ApiAdminLicenseInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppBillingRoute: typeof AuthAppBillingRoute
  AuthAppDownloadsRoute: typeof AuthAppDownloadsRoute
  AuthAppSupportRoute: typeof AuthAppSupportRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppBillingRoute: AuthAppBillingRoute,
  AuthAppDownloadsRoute: AuthAppDownloadsRoute,
  AuthAppSupportRoute: AuthAppSupportRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  DownloadRoute: DownloadRoute,
  PrivacyRoute: PrivacyRoute,
  RoadmapRoute: RoadmapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiChangelogRoute: ApiChangelogRoute,
  ApiReleasesRoute: ApiReleasesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLicenseActivateRoute: ApiLicenseActivateRoute,
  ApiLicenseCheckRoute: ApiLicenseCheckRoute,
  ApiLicenseDeactivateRoute: ApiLicenseDeactivateRoute,
  ApiLicensePubkeyRoute: ApiLicensePubkeyRoute,
  ApiWebhooksProviderRoute: ApiWebhooksProviderRoute,
  ApiAdminLicenseInfoRoute: ApiAdminLicenseInfoRoute,
  ApiAdminLicenseRevokeRoute: ApiAdminLicenseRevokeRoute,
  ApiAdminLicenseUnrevokeRoute: ApiAdminLicenseUnrevokeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
